# Generated by Django 5.2.16 on 2026-07-25 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=2, unique=True)),
                ('nama_bab', models.CharField(max_length=100)),
                ('urutan', models.IntegerField()),
            ],
            options={
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='Desa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_desa', models.CharField(max_length=100)),
                ('kecamatan', models.CharField(max_length=100)),
                ('kabupaten', models.CharField(max_length=100)),
                ('tahun_profil', models.IntegerField()),
                ('garis_bujur', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('garis_lintang', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('status_wilayah', models.CharField(blank=True, max_length=50)),
                ('sejarah_desa', models.TextField(blank=True)),
                ('nama_kepala_desa', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ItemKuesioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_item', models.IntegerField(unique=True)),
                ('pertanyaan', models.TextField()),
                ('konsep_definisi', models.TextField(blank=True)),
                ('tipe_data', models.CharField(choices=[('angka', 'Angka'), ('teks', 'Teks'), ('pilihan', 'Pilihan (Ada/Tidak Ada, dll)')], max_length=20)),
                ('satuan', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['no_item'],
            },
        ),
        migrations.CreateModel(
            name='AturanValidasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi_rule', models.TextField()),
                ('tipe_rule', models.CharField(max_length=50)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aturan_list', to='desa.itemkuesioner')),
            ],
        ),
        migrations.CreateModel(
            name='SubbabTabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_tabel', models.CharField(max_length=10)),
                ('nama_tabel', models.CharField(max_length=150)),
                ('urutan', models.IntegerField()),
                ('bab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subbab_list', to='desa.bab')),
            ],
            options={
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='ItemSubbab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kolom', models.CharField(max_length=150)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pemetaan_subbab', to='desa.itemkuesioner')),
                ('subbab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_list', to='desa.subbabtabel')),
            ],
        ),
        migrations.CreateModel(
            name='JawabanKuesioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.CharField(blank=True, max_length=255, null=True)),
                ('tanggal_input', models.DateTimeField(auto_now=True)),
                ('desa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jawaban_list', to='desa.desa')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jawaban_list', to='desa.itemkuesioner')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('desa', 'item')},
            },
        ),
    ]
