# Generated by Django 5.2.16 on 2026-07-26 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='desa',
            name='foto_kepala_desa',
            field=models.ImageField(blank=True, null=True, upload_to='foto_kepala_desa/'),
        ),
        migrations.AddField(
            model_name='desa',
            name='peta_wilayah',
            field=models.ImageField(blank=True, null=True, upload_to='peta_wilayah/'),
        ),
    ]
