# Generated by Django 5.2.16 on 2026-07-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desa', '0002_desa_foto_kepala_desa_desa_peta_wilayah'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemkuesioner',
            name='pilihan_jawaban',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
