# Generated by Django 5.2.16 on 2026-07-28 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desa', '0003_itemkuesioner_pilihan_jawaban'),
    ]

    operations = [
        migrations.AddField(
            model_name='subbabtabel',
            name='label_kategori',
            field=models.CharField(default='Uraian', help_text="Judul kolom ke-2, contoh: 'Organisasi', 'Jenis Sarana'", max_length=100),
        ),
        migrations.AddField(
            model_name='subbabtabel',
            name='label_nilai',
            field=models.CharField(default='Jumlah', help_text="Judul kolom ke-3, contoh: 'Jumlah Organisasi'", max_length=100),
        ),
    ]
