# Generated by Django 5.2.16 on 2026-08-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desa', '0004_subbabtabel_label_kategori_subbabtabel_label_nilai'),
    ]

    operations = [
        migrations.AddField(
            model_name='desa',
            name='keadaan_data',
            field=models.CharField(blank=True, help_text='Periode data, contoh: Desember 2024 dan April 2025', max_length=100),
        ),
        migrations.AddField(
            model_name='desa',
            name='nomor_kode',
            field=models.CharField(blank=True, help_text='Nomor kode desa/kelurahan, contoh: 2007', max_length=20),
        ),
    ]
