# Generated by Django 5.2.16 on 2026-08-26 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desa', '0005_desa_keadaan_data_desa_nomor_kode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AturanValidasi',
        ),
    ]
