from django.core.management.base import BaseCommand
from desa.models import Bab, SubbabTabel, ItemKuesioner, ItemSubbab


BAB_LIST = [
    ("A", "Perkembangan Penduduk", 1),
    ("B", "Ekonomi Masyarakat", 2),
    ("C", "Pendapatan", 3),
    ("D", "Penguasaan Aset Ekonomi Masyarakat", 4),
    ("E", "Pendidikan Masyarakat", 5),
    ("F", "Kesehatan Masyarakat", 6),
    ("G", "Keamanan, Ketertiban, dan Bencana", 7),
    ("H", "Kedaulatan Politik Masyarakat", 8),
    ("I", "Lembaga Kemasyarakatan", 9),
    ("J", "Pemerintahan Desa dan Kelurahan", 10),
    ("K", "Prasarana Perhubungan, Energi, dan Komunikasi", 11),
]

SUBBAB_LIST = [
    ("A.1", "A", "Jumlah Penduduk", 1),
    ("A.2", "A", "Keluarga dan Kelistrikan", 2),
    ("B.1", "B", "Sarana Perdagangan Dasar", 1),
    ("B.2", "B", "Kelembagaan Ekonomi Desa", 2),
    ("B.3", "B", "Pariwisata", 3),
    ("B.4", "B", "Sarana Perdagangan dan Industri", 4),
    ("D.1", "D", "Status Pertanahan", 1),
    ("D.2", "D", "Alat Transportasi", 2),
    ("D.3", "D", "Peternakan", 3),
    ("E.1", "E", "Jumlah Satuan Pendidikan", 1),
    ("F.1", "F", "Fasilitas Kesehatan", 1),
    ("G.1", "G", "Kesiapsiagaan Bencana", 1),
    ("G.2", "G", "Keamanan dan Ketertiban Lingkungan", 2),
    ("I.1", "I", "Pembinaan RT/RW", 1),
    ("I.2", "I", "Kelembagaan Keagamaan", 2),
    ("I.3", "I", "Perkumpulan Olahraga", 3),
    ("I.4", "I", "Kesenian/Kebudayaan", 4),
    ("I.5", "I", "Organisasi Sosial", 5),
    ("I.6", "I", "Tenaga Kerja", 6),
    ("J.1", "J", "Aparatur Pemerintahan Desa", 1),
    ("J.2", "J", "Data Kepala Desa dan Sekretaris Desa", 2),
    ("J.3", "J", "Badan Permusyawaratan Desa (BPD)", 3),
    ("J.4", "J", "Sistem Administrasi dan Keuangan Desa", 4),
    ("J.5", "J", "Aset dan Kekayaan Desa", 5),
    ("K.1", "K", "Kondisi Jalan dan Angkutan", 1),
    ("K.2", "K", "Orbitasi", 2),
    ("K.3", "K", "Kondisi Energi dan Bahan Bakar Rumah Tangga", 3),
    ("K.4", "K", "Kondisi Komunikasi dan Layanan Pos", 4),
]

# format: (no_item, pertanyaan PERSIS SESUAI BUKU PEDOMAN, tipe_data, satuan)
# DIPERBAIKI: sebelumnya penomoran loncat dari 8 langsung ke 10 (item 9
# "Berapa jumlah penduduk laki-laki?" tidak pernah tersimpan), sehingga semua
# item no_item 10 s.d. 144 sebenarnya bergeser dari nomor aslinya. Sudah
# dirapikan jadi 1-143 berurutan sesuai kuesioner asli.
ITEMS = [
    (1, 'Apakah status pemerintahan wilayah administratif?', 'pilihan', ''),
    (2, 'Apakah ada wilayah desa ini yang berbatasan langsung dengan laut?', 'pilihan', ''),
    (3, 'Jika berbatasan dengan laut, pemanfaatan laut untuk Perikanan tangkap (mencakup seluruh biota laut)?', 'pilihan', ''),
    (4, 'Jika berbatasan dengan laut, pemanfaatan laut untuk Perikanan budidaya (mencakup seluruh biota laut)?', 'pilihan', ''),
    (5, 'Jika berbatasan dengan laut, pemanfaatan laut untuk Tambak garam?', 'pilihan', ''),
    (6, 'Jika berbatasan dengan laut, pemanfaatan laut untuk Wisata bahari?', 'pilihan', ''),
    (7, 'Jika berbatasan dengan laut, pemanfaatan laut untuk Transportasi umum?', 'pilihan', ''),
    (8, 'Apakah lokasi wilayah administratif desa ini terhadap kawasan hutan/hutan?', 'pilihan', ''),
    (9, 'Berapa jumlah penduduk laki-laki?', 'angka', 'jiwa'),
    (10, 'Berapa jumlah penduduk perempuan?', 'angka', 'jiwa'),
    (11, 'Berapa jumlah keluarga?', 'angka', 'KK'),
    (12, 'Berapa jumlah keluarga pertanian (tanaman pangan, hortikultura, perkebunan, peternakan, perikanan, kehutanan)?', 'angka', 'KK'),
    (13, 'Berapa jumlah keluarga pengguna listrik PLN?', 'angka', 'KK'),
    (14, 'Berapa jumlah keluarga pengguna listrik Non PLN?', 'angka', 'KK'),
    (15, 'Berapa jumlah keluarga bukan pengguna listrik?', 'angka', 'KK'),
    (16, 'Apakah terdapat penerangan di jalan utama desa ini?', 'pilihan', ''),
    (17, 'Mayoritas sumber penerangan di jalan utama desa ini?', 'pilihan', ''),
    (18, 'Apakah bahan bakar yang digunakan untuk memasak sebagian besar keluarga?', 'pilihan', ''),
    (19, 'Apakah memiliki sistem peringatan dini bencana alam?', 'pilihan', ''),
    (20, 'Apakah memiliki sistem peringatan dini khusus tsunami?', 'pilihan', ''),
    (21, 'Apakah memiliki perlengkapan keselamatan (perahu karet, tenda, masker, dll.) jika terjadi bencana atau keadaan darurat?', 'pilihan', ''),
    (22, 'Apakah memiliki rambu-rambu dan jalur evakuasi bencana?', 'pilihan', ''),
    (23, 'Apakah melakukan kegiatan pembuatan, perawatan, atau normalisasi: sungai, kanal, tanggul, parit, drainase, waduk, pantai, dll.?', 'pilihan', ''),
    (24, 'Berapa jumlah TK negeri?', 'angka', 'unit'),
    (25, 'Berapa jumlah TK swasta?', 'angka', 'unit'),
    (26, 'Berapa jumlah RA/BA negeri?', 'angka', 'unit'),
    (27, 'Berapa jumlah RA/BA swasta?', 'angka', 'unit'),
    (28, 'Berapa jumlah SD negeri?', 'angka', 'unit'),
    (29, 'Berapa jumlah SD swasta?', 'angka', 'unit'),
    (30, 'Berapa jumlah MI negeri?', 'angka', 'unit'),
    (31, 'Berapa jumlah MI swasta?', 'angka', 'unit'),
    (32, 'Berapa jumlah SMP negeri?', 'angka', 'unit'),
    (33, 'Berapa jumlah SMP swasta?', 'angka', 'unit'),
    (34, 'Berapa jumlah MTs negeri?', 'angka', 'unit'),
    (35, 'Berapa jumlah MTs swasta?', 'angka', 'unit'),
    (36, 'Berapa jumlah SMA negeri?', 'angka', 'unit'),
    (37, 'Berapa jumlah SMA swasta?', 'angka', 'unit'),
    (38, 'Berapa jumlah MA negeri?', 'angka', 'unit'),
    (39, 'Berapa jumlah MA swasta?', 'angka', 'unit'),
    (40, 'Berapa jumlah SMK negeri?', 'angka', 'unit'),
    (41, 'Berapa jumlah SMK swasta?', 'angka', 'unit'),
    (42, 'Berapa jumlah Akademi/Perguruan Tinggi Negeri?', 'angka', 'unit'),
    (43, 'Berapa jumlah Akademi/Perguruan Tinggi Swasta?', 'angka', 'unit'),
    (44, 'Berapa jumlah Rumah Sakit?', 'angka', 'unit'),
    (45, 'Berapa jumlah puskesmas dengan rawat inap?', 'angka', 'unit'),
    (46, 'Berapa jumlah puskesmas tanpa rawat inap?', 'angka', 'unit'),
    (47, 'Berapa jumlah puskesmas pembantu?', 'angka', 'unit'),
    (48, 'Berapa jumlah praktik mandiri dokter?', 'angka', 'unit'),
    (49, 'Berapa jumlah praktik mandiri bidan?', 'angka', 'unit'),
    (50, 'Berapa jumlah poskesdes (pos kesehatan desa)?', 'angka', 'unit'),
    (51, 'Berapa jumlah polindes (pondok bersalin desa)?', 'angka', 'unit'),
    (52, 'Berapa jumlah apotek?', 'angka', 'unit'),
    (53, 'Berapa jumlah toko obat/jamu?', 'angka', 'unit'),
    (54, 'Berapa jumlah posyandu aktif?', 'angka', 'unit'),
    (55, 'Berapa jumlah Posyandu dengan kegiatan/pelayanan setiap sebulan sekali?', 'angka', 'unit'),
    (56, 'Berapa jumlah Posyandu dengan kegiatan/pelayanan setiap 2 bulan sekali atau lebih?', 'angka', 'unit'),
    (57, 'Berapa jumlah Pos Pembinaan Terpadu (Posbindu)?', 'angka', 'unit'),
    (58, 'Apakah lalu lintas dari/ke desa ini yang digunakan melalui?', 'pilihan', ''),
    (59, 'Apakah jenis permukaan jalan darat antar desa ini yang terluas?', 'pilihan', ''),
    (60, 'Apakah jalan darat antar desa ini dapat dilalui kendaraan bermotor roda 4 atau lebih?', 'pilihan', ''),
    (61, 'Apakah ada angkutan umum?', 'pilihan', ''),
    (62, 'Jumlah hari operasional angkutan umum yang utama?', 'angka', 'hari'),
    (63, 'Jumlah jam operasi angkutan umum yang utama?', 'angka', 'jam'),
    (64, 'Jumlah jenis angkutan umum yang utama dari kantor kepala desa ke kantor camat?', 'pilihan', ''),
    (65, 'Berapa jarak tempuh dari kantor kepala desa ke kantor camat (km)?', 'angka', 'km'),
    (66, 'Berapa waktu tempuh dari kantor kepala desa ke kantor camat (jam)?', 'angka', 'jam'),
    (67, 'Berapa waktu tempuh dari kantor kepala desa ke kantor camat (menit)?', 'angka', 'menit'),
    (68, 'Berapa biaya transportasi dari kantor kepala desa/lurah ke kantor camat (ribu rupiah)?', 'angka', 'ribu rupiah'),
    (69, 'Apakah jenis angkutan umum yang utama dari kantor kepala desa ke kantor bupati?', 'pilihan', ''),
    (70, 'Berapa jarak tempuh dari kantor kepala desa ke kantor bupati (km)?', 'angka', 'km'),
    (71, 'Berapa waktu tempuh dari kantor kepala desa ke kantor bupati (jam)?', 'angka', 'jam'),
    (72, 'Berapa waktu tempuh dari kantor kepala desa ke kantor bupati (menit)?', 'angka', 'menit'),
    (73, 'Berapa biaya transportasi dari kantor kepala desa/lurah ke kantor bupati (ribu rupiah)?', 'angka', 'ribu rupiah'),
    (74, 'Berapa jumlah keluarga yang berlangganan telepon kabel?', 'angka', 'KK'),
    (75, 'Apakah keberadaan warga yang menggunakan telepon seluler/handphone?', 'pilihan', ''),
    (76, 'Berapa jumlah menara Base Transceiver Station (BTS)?', 'angka', 'unit'),
    (77, 'Berapa jumlah operator layanan komunikasi telepon seluler/handphone yang menjangkau di desa ini?', 'angka', 'operator'),
    (78, 'Apakah keberadaan sinyal telepon seluler/handphone di sebagian besar wilayah desa ini?', 'pilihan', ''),
    (79, 'Apakah jenis sinyal internet telepon seluler/handphone di sebagian besar wilayah di desa ini?', 'pilihan', ''),
    (80, 'Apakah terdapat keberadaan kantor pos/pos pembantu/rumah pos?', 'pilihan', ''),
    (81, 'Apakah terdapat keberadaan layanan pos keliling?', 'pilihan', ''),
    (82, 'Apakah terdapat keberadaan perusahaan/agen jasa ekspedisi (pengiriman barang/dokumen) swasta?', 'pilihan', ''),
    (83, 'Apakah terdapat keberadaan pangkalan/agen/penjual minyak tanah (termasuk penjual minyak tanah keliling)?', 'pilihan', ''),
    (84, 'Apakah terdapat keberadaan pangkalan/agen/penjual LPG (warung, toko, supermarket, penjual gas keliling)?', 'pilihan', ''),
    (85, 'Berapa jumlah Bank Umum Pemerintah (BRI, BNI, Mandiri, BPD, BTN)?', 'angka', 'unit'),
    (86, 'Berapa jumlah Bank Umum Swasta (BCA, Permata, Sinarmas, CIMB, dll)?', 'angka', 'unit'),
    (87, 'Berapa jumlah Bank Perkreditan Rakyat (BPR)?', 'angka', 'unit'),
    (88, 'Berapa jumlah Koperasi Unit Desa (KUD)?', 'pilihan', ''),
    (89, 'Berapa jumlah Koperasi Industri Kecil dan Kerajinan Rakyat (Kopinkra)/Usaha mikro?', 'angka', 'unit'),
    (90, 'Berapa jumlah Koperasi Simpan Pinjam (KSP/Kospin)?', 'angka', 'unit'),
    (91, 'Berapa jumlah Koperasi lainnya?', 'angka', 'unit'),
    (92, 'Apakah terdapat fasilitas Kredit Usaha Rakyat (KUR) yang diterima warga desa ini selama setahun terakhir?', 'pilihan', ''),
    (93, 'Apakah terdapat fasilitas Kredit Ketahanan Pangan dan Energi (KKP-E) yang diterima warga desa ini selama setahun terakhir?', 'pilihan', ''),
    (94, 'Apakah terdapat fasilitas Kredit Usaha Kecil (KUK) yang diterima warga desa ini selama setahun terakhir?', 'pilihan', ''),
    (95, 'Apakah terdapat fasilitas Kelompok Usaha Bersama (KUBE) yang diterima warga desa ini selama setahun terakhir?', 'pilihan', ''),
    (96, 'Berapa jumlah kelompok pertokoan?', 'angka', 'unit'),
    (97, 'Berapa jumlah pasar dengan bangunan permanen?', 'angka', 'unit'),
    (98, 'Berapa jumlah pasar dengan bangunan semi permanen?', 'angka', 'unit'),
    (99, 'Berapa jumlah pasar tanpa bangunan?', 'angka', 'unit'),
    (100, 'Berapa jumlah minimarket/swalayan/supermarket?', 'angka', 'unit'),
    (101, 'Berapa jumlah restoran/rumah makan?', 'angka', 'unit'),
    (102, 'Berapa jumlah warung/kedai makanan minuman?', 'angka', 'unit'),
    (103, 'Berapa jumlah hotel?', 'angka', 'unit'),
    (104, 'Berapa jumlah penginapan: hostel/motel/losmen/wisma?', 'angka', 'unit'),
    (105, 'Berapa jumlah toko/warung kelontong?', 'angka', 'unit'),
    (106, 'Berapa jumlah Industri mikro dan kecil (memiliki tenaga kerja kurang dari 20 pekerja)?', 'angka', 'unit'),
    (107, 'Berapa jumlah Sentra Industri?', 'angka', 'unit'),
    (108, 'Jika terdapat sentra industri, tuliskan produk pada sentra industri yang mempunyai muatan usaha terbanyak?', 'teks', ''),
    (109, 'Apakah terdapat keberadaan produk barang unggulan/utama di desa ini?', 'pilihan', ''),
    (110, 'Apakah terdapat pembangunan/pemeliharaan pos keamanan lingkungan?', 'pilihan', ''),
    (111, 'Apakah terdapat pembentukan/pengaturan regu keamanan?', 'pilihan', ''),
    (112, 'Apakah terdapat penambahan jumlah anggota hansip/linmas?', 'pilihan', ''),
    (113, 'Apakah terdapat pelaporan tamu yang menginap lebih dari 24 jam ke aparat lingkungan?', 'pilihan', ''),
    (114, 'Apakah terdapat pengaktifan sistem keamanan lingkungan berasal dari inisiatif warga?', 'pilihan', ''),
    (115, 'Apakah terdapat keberadaan sistem informasi desa (SID)?', 'pilihan', ''),
    (116, 'Jika ada SID, kapan bulan terakhir diperbaharui?', 'pilihan', ''),
    (117, 'Jika ada SID, kapan tahun terakhir diperbaharui?', 'angka', 'tahun'),
    (118, 'Apakah terdapat penggunaan sistem keuangan desa?', 'pilihan', ''),
    (119, 'Berapa jumlah unit usaha BUMDes?', 'angka', 'unit'),
    (120, 'Apakah terdapat tanah kas desa/ulayat?', 'pilihan', ''),
    (121, 'Apakah terdapat tambatan perahu?', 'pilihan', ''),
    (122, 'Apakah terdapat pasar (pasar desa, pasar hewan, pelelangan ikan yang dikelola desa, pelelangan hasil pertanian)?', 'pilihan', ''),
    (123, 'Apakah terdapat bangunan milik desa (balai desa, balai rakyat, lapangan olah raga, dll)?', 'pilihan', ''),
    (124, 'Apakah terdapat hutan milik desa?', 'pilihan', ''),
    (125, 'Apakah terdapat mata air milik desa?', 'pilihan', ''),
    (126, 'Apakah terdapat tempat wisata/Pemandian umum?', 'pilihan', ''),
    (127, 'Apakah terdapat aset desa lainnya (kekayaan asli desa lainnya, hibah/sumbangan/sejenisnya dll)?', 'pilihan', ''),
    (128, 'Berapa jumlah peraturan desa tahun 2024?', 'angka', 'perdes'),
    (129, 'Apakah terdapat keberadaan kepala desa?', 'pilihan', ''),
    (130, 'Berapa umur kepala desa?', 'angka', 'tahun'),
    (131, 'Apakah jenis kelamin kepala desa?', 'pilihan', ''),
    (132, 'Apakah pendidikan tertinggi yang ditamatkan Kepala Desa/Lurah?', 'pilihan', ''),
    (133, 'Apakah terdapat keberadaan Sekretaris Desa/Sekretaris Kelurahan?', 'pilihan', ''),
    (134, 'Berapa umur Sekretaris Desa/Sekretaris Kelurahan?', 'angka', 'tahun'),
    (135, 'Apakah jenis kelamin Sekretaris Desa/Sekretaris Kelurahan?', 'pilihan', ''),
    (136, 'Apakah pendidikan tertinggi yang ditamatkan Sekretaris Desa/Sekretaris Kelurahan?', 'pilihan', ''),
    (137, 'Berapa jumlah aparatur pemerintahan Sekretariat Desa/Sekretariat Kelurahan?', 'angka', 'orang'),
    (138, 'Berapa jumlah aparatur pemerintahan Pelaksana Teknis?', 'angka', 'orang'),
    (139, 'Berapa jumlah aparatur pemerintahan Pelaksana Kewilayahan?', 'angka', 'orang'),
    (140, 'Berapa jumlah aparatur pemerintahan Pegawai desa ini lainnya?', 'angka', 'orang'),
    (141, 'Apakah terdapat badan Permusyawaratan Desa/Lembaga Musyawarah Kelurahan?', 'pilihan', ''),
    (142, 'Jika ada, apakah ada anggota yang perempuan?', 'pilihan', ''),
    (143, 'Berapa jumlah musyawarah desa selama setahun terakhir?', 'angka', 'kali'),
]

# format: no_item -> "opsi1,opsi2,opsi3"
PILIHAN_JAWABAN = {
    1: 'Kelurahan/ Desa/ Nagari',
    2: 'Ada/ Tidak ada',
    3: 'Ada/ Tidak ada',
    4: 'Ada/ Tidak ada',
    5: 'Ada/ Tidak ada',
    6: 'Ada/ Tidak ada',
    7: 'Ada/ Tidak ada',
    8: 'Didalam / Di luar kawasan hutan',
    16: 'Ada (sebagian besar, kecil) / Tidak ada',
    17: 'PLN / Non PLN',
    18: 'LPG (3 Kg, 5 Kg, 12 KG) Kayu bakar, Lainnya',
    19: 'Ada / Tidak ada',
    20: 'Potensi / Bukan Potensi',
    21: 'Ada / Tidak ada',
    22: 'Ada / Tidak ada',
    23: 'Ada / Tidak ada',
    58: 'Darat / Sungai / Laut',
    59: 'Aspal/beton / Tanah / Kayu / Air',
    60: 'Sepanjang tahun',
    61: 'Ada (trayek tetap, tidak tetap), Tidak',
    62: 'Setiap hari, tidak harian',
    63: 'Siang, Malam, Setiap saat',
    75: 'Ada (sebagian besar, kecil) / Tidak ada',
    78: 'Ada (sinyal kuat, lemah) / Tidak ada',
    79: '5G/4G/LTE',
    80: 'Ada / Tidak ada',
    81: 'Ada / Tidak ada',
    82: 'Ada / Tidak ada',
    83: 'Ada / Tidak ada',
    84: 'Ada / Tidak ada',
    92: 'Ada / Tidak ada',
    93: 'Ada / Tidak ada',
    94: 'Ada / Tidak ada',
    95: 'Ada / Tidak ada',
    109: 'Ada / Tidak ada',
    110: 'Ada / Tidak ada',
    111: 'Ada / Tidak ada',
    112: 'Ada / Tidak ada',
    113: 'Ada / Tidak ada',
    114: 'Ada / Tidak ada',
    115: 'Ada, (diperbaharui, tidak diperbaharui) / Tidak Ada',
    118: 'Ada, (diperbaharui, tidak diperbaharui) / Tidak Ada',
    120: 'Ada / Tidak ada',
    121: 'Ada / Tidak ada',
    122: 'Ada / Tidak ada',
    123: 'Ada / Tidak ada',
    124: 'Ada / Tidak ada',
    125: 'Ada / Tidak ada',
    126: 'Ada / Tidak ada',
    127: 'Ada / Tidak ada',
    129: 'Ada / Tidak ada',
    131: 'Laki-laki / Perempuan',
    132: 'SMA / Akadaemi/DIII / S1 / S2 / S3',
    133: 'Ada / Tidak ada',
    135: 'Laki-laki / Perempuan',
    136: 'SMA / Akadaemi/DIII / S1 / S2 / S3',
    141: 'Ada / Tidak ada',
    142: 'Ada / Tidak ada',
}

# format: no_item -> label pendek untuk ditampilkan di kolom tabel Word
NAMA_KOLOM_OVERRIDE = {
    9: 'Laki-laki',
    10: 'Perempuan',
    11: 'Jumlah Keluarga',
    12: 'Keluarga Pertanian',
    13: 'Pengguna Listrik PLN',
    14: 'Pengguna Listrik Non PLN',
    15: 'Bukan Pengguna Listrik',
    16: 'Penerangan Jalan Utama',
    17: 'Sumber Penerangan Jalan Utama',
    18: 'Bahan Bakar Memasak',
    19: 'Sistem Peringatan Dini Bencana',
    20: 'Sistem Peringatan Dini Tsunami',
    21: 'Perlengkapan Keselamatan Bencana',
    22: 'Rambu dan Jalur Evakuasi',
    23: 'Perawatan/Normalisasi Sungai dan Sejenisnya',
    24: 'TK Negeri',
    25: 'TK Swasta',
    26: 'RA/BA Negeri',
    27: 'RA/BA Swasta',
    28: 'SD Negeri',
    29: 'SD Swasta',
    30: 'MI Negeri',
    31: 'MI Swasta',
    32: 'SMP Negeri',
    33: 'SMP Swasta',
    34: 'MTs Negeri',
    35: 'MTs Swasta',
    36: 'SMA Negeri',
    37: 'SMA Swasta',
    38: 'MA Negeri',
    39: 'MA Swasta',
    40: 'SMK Negeri',
    41: 'SMK Swasta',
    42: 'Akademi/Perguruan Tinggi Negeri',
    43: 'Akademi/Perguruan Tinggi Swasta',
    44: 'Rumah Sakit',
    45: 'Puskesmas Rawat Inap',
    46: 'Puskesmas Tanpa Rawat Inap',
    47: 'Puskesmas Pembantu',
    48: 'Praktik Mandiri Dokter',
    49: 'Praktik Mandiri Bidan',
    50: 'Poskesdes',
    51: 'Polindes',
    52: 'Apotek',
    53: 'Toko Obat/Jamu',
    54: 'Posyandu Aktif',
    55: 'Posyandu (Pelayanan Sebulan Sekali)',
    56: 'Posyandu (Pelayanan 2 Bulan Sekali atau Lebih)',
    57: 'Pos Pembinaan Terpadu (Posbindu)',
    58: 'Jalur Lalu Lintas Utama',
    59: 'Jenis Permukaan Jalan',
    60: 'Jalan Dapat Dilalui Roda 4',
    61: 'Keberadaan Angkutan Umum',
    62: 'Hari Operasional Angkutan Umum',
    63: 'Jam Operasi Angkutan Umum',
    64: 'Jenis Angkutan ke Kantor Camat',
    65: 'Jarak ke Kantor Camat (Km)',
    66: 'Waktu Tempuh ke Kantor Camat (Jam)',
    67: 'Waktu Tempuh ke Kantor Camat (Menit)',
    68: 'Biaya Transportasi ke Kantor Camat',
    69: 'Jenis Angkutan ke Kantor Bupati',
    70: 'Jarak ke Kantor Bupati (Km)',
    71: 'Waktu Tempuh ke Kantor Bupati (Jam)',
    72: 'Waktu Tempuh ke Kantor Bupati (Menit)',
    73: 'Biaya Transportasi ke Kantor Bupati',
    74: 'Pelanggan Telepon Kabel',
    75: 'Pengguna Telepon Seluler',
    76: 'Menara BTS',
    77: 'Operator Layanan Komunikasi',
    78: 'Sinyal Telepon Seluler',
    79: 'Jenis Sinyal Internet',
    80: 'Kantor Pos/Pos Pembantu',
    81: 'Layanan Pos Keliling',
    82: 'Agen Jasa Ekspedisi',
    83: 'Agen/Penjual Minyak Tanah',
    84: 'Agen/Penjual LPG',
    85: 'Bank Umum Pemerintah',
    86: 'Bank Umum Swasta',
    87: 'Bank Perkreditan Rakyat (BPR)',
    88: 'Koperasi Unit Desa (KUD)',
    89: 'Kopinkra/Usaha Mikro',
    90: 'Koperasi Simpan Pinjam (KSP)',
    91: 'Koperasi Lainnya',
    92: 'Kredit Usaha Rakyat (KUR)',
    93: 'Kredit Ketahanan Pangan dan Energi (KKP-E)',
    94: 'Kredit Usaha Kecil (KUK)',
    95: 'Kelompok Usaha Bersama (KUBE)',
    96: 'Kelompok Pertokoan',
    97: 'Pasar Bangunan Permanen',
    98: 'Pasar Bangunan Semi Permanen',
    99: 'Pasar Tanpa Bangunan',
    100: 'Minimarket/Swalayan/Supermarket',
    101: 'Restoran/Rumah Makan',
    102: 'Warung/Kedai Makanan Minuman',
    103: 'Hotel',
    104: 'Penginapan (Hostel/Motel/Losmen/Wisma)',
    105: 'Toko/Warung Kelontong',
    106: 'Industri Mikro dan Kecil',
    107: 'Sentra Industri',
    108: 'Produk Unggulan Sentra Industri',
    109: 'Produk Unggulan Desa',
    110: 'Pos Keamanan Lingkungan',
    111: 'Regu Keamanan',
    112: 'Penambahan Anggota Hansip/Linmas',
    113: 'Pelaporan Tamu Menginap',
    114: 'Sistem Keamanan Inisiatif Warga',
    115: 'Keberadaan Sistem Informasi Desa (SID)',
    116: 'Bulan Terakhir Update SID',
    117: 'Tahun Terakhir Update SID',
    118: 'Penggunaan Sistem Keuangan Desa',
    119: 'Unit Usaha BUMDes',
    120: 'Tanah Kas Desa/Ulayat',
    121: 'Tambatan Perahu',
    122: 'Pasar Milik Desa',
    123: 'Bangunan Milik Desa',
    124: 'Hutan Milik Desa',
    125: 'Mata Air Milik Desa',
    126: 'Tempat Wisata/Pemandian Umum',
    127: 'Aset Desa Lainnya',
    128: 'Jumlah Peraturan Desa (Perdes)',
    129: 'Keberadaan Kepala Desa',
    130: 'Umur Kepala Desa',
    131: 'Jenis Kelamin Kepala Desa',
    132: 'Pendidikan Kepala Desa',
    133: 'Keberadaan Sekretaris Desa',
    134: 'Umur Sekretaris Desa',
    135: 'Jenis Kelamin Sekretaris Desa',
    136: 'Pendidikan Sekretaris Desa',
    137: 'Aparatur Sekretariat Desa',
    138: 'Aparatur Pelaksana Teknis',
    139: 'Aparatur Pelaksana Kewilayahan',
    140: 'Pegawai Desa Lainnya',
    141: 'Keberadaan BPD',
    142: 'Anggota Perempuan BPD',
    143: 'Jumlah Musyawarah Desa',
}

# format: (no_item, kode_tabel)
MAPPING = [
    (9, 'A.1'), (10, 'A.1'), (11, 'A.1'), (12, 'A.2'), (13, 'A.2'), (14, 'A.2'), (15, 'A.2'),
    (83, 'B.1'), (84, 'B.1'),
    (85, 'B.2'), (86, 'B.2'), (87, 'B.2'), (88, 'B.2'), (89, 'B.2'), (90, 'B.2'),
    (91, 'B.2'), (92, 'B.2'), (93, 'B.2'), (94, 'B.2'), (95, 'B.2'), (119, 'B.2'),
    (126, 'B.3'),
    (96, 'B.4'), (97, 'B.4'), (98, 'B.4'), (99, 'B.4'), (100, 'B.4'), (101, 'B.4'),
    (102, 'B.4'), (103, 'B.4'), (104, 'B.4'), (105, 'B.4'), (106, 'B.4'), (107, 'B.4'),
    (108, 'B.4'), (109, 'B.4'),
    (24, 'E.1'), (25, 'E.1'), (26, 'E.1'), (27, 'E.1'), (28, 'E.1'), (29, 'E.1'),
    (30, 'E.1'), (31, 'E.1'), (32, 'E.1'), (33, 'E.1'), (34, 'E.1'), (35, 'E.1'),
    (36, 'E.1'), (37, 'E.1'), (38, 'E.1'), (39, 'E.1'), (40, 'E.1'), (41, 'E.1'),
    (42, 'E.1'), (43, 'E.1'),
    (44, 'F.1'), (45, 'F.1'), (46, 'F.1'), (47, 'F.1'), (48, 'F.1'), (49, 'F.1'),
    (50, 'F.1'), (51, 'F.1'), (52, 'F.1'), (53, 'F.1'), (54, 'F.1'), (55, 'F.1'),
    (56, 'F.1'), (57, 'F.1'),
    (19, 'G.1'), (20, 'G.1'), (21, 'G.1'), (22, 'G.1'), (23, 'G.1'),
    (110, 'G.2'), (111, 'G.2'), (112, 'G.2'), (113, 'G.2'), (114, 'G.2'),
    (137, 'J.1'), (138, 'J.1'), (139, 'J.1'), (140, 'J.1'),
    (129, 'J.2'), (130, 'J.2'), (131, 'J.2'), (132, 'J.2'),
    (133, 'J.2'), (134, 'J.2'), (135, 'J.2'), (136, 'J.2'),
    (141, 'J.3'), (142, 'J.3'), (143, 'J.3'),
    (115, 'J.4'), (116, 'J.4'), (117, 'J.4'), (118, 'J.4'), (128, 'J.4'),
    (119, 'J.5'), (120, 'J.5'), (121, 'J.5'), (122, 'J.5'), (123, 'J.5'),
    (124, 'J.5'), (125, 'J.5'), (126, 'J.5'), (127, 'J.5'),
    (58, 'K.1'), (59, 'K.1'), (60, 'K.1'), (61, 'K.1'), (62, 'K.1'), (63, 'K.1'),
    (64, 'K.2'), (65, 'K.2'), (66, 'K.2'), (67, 'K.2'), (68, 'K.2'),
    (69, 'K.2'), (70, 'K.2'), (71, 'K.2'), (72, 'K.2'), (73, 'K.2'),
    (16, 'K.3'), (17, 'K.3'), (18, 'K.3'),
    (74, 'K.4'), (75, 'K.4'), (76, 'K.4'), (77, 'K.4'), (78, 'K.4'),
    (79, 'K.4'), (80, 'K.4'), (81, 'K.4'), (82, 'K.4'),
]


class Command(BaseCommand):
    help = "Mengisi data master: Bab, SubbabTabel, ItemKuesioner, dan pemetaannya"

    def handle(self, *args, **options):
        bab_map = {}
        for kode, nama, urutan in BAB_LIST:
            obj, _ = Bab.objects.update_or_create(
                kode=kode, defaults={"nama_bab": nama, "urutan": urutan}
            )
            bab_map[kode] = obj
        self.stdout.write(self.style.SUCCESS(f"{len(BAB_LIST)} Bab tersimpan"))

        subbab_map = {}
        for kode_tabel, bab_kode, nama_tabel, urutan in SUBBAB_LIST:
            obj, _ = SubbabTabel.objects.update_or_create(
                kode_tabel=kode_tabel,
                defaults={"bab": bab_map[bab_kode], "nama_tabel": nama_tabel, "urutan": urutan},
            )
            subbab_map[kode_tabel] = obj
        self.stdout.write(self.style.SUCCESS(f"{len(SUBBAB_LIST)} Sub-tabel tersimpan"))

        item_map = {}
        for no_item, pertanyaan, tipe_data, satuan in ITEMS:
            obj, _ = ItemKuesioner.objects.update_or_create(
                no_item=no_item,
                defaults={
                    "pertanyaan": pertanyaan,
                    "tipe_data": tipe_data,
                    "satuan": satuan,
                    "pilihan_jawaban": PILIHAN_JAWABAN.get(no_item, ""),
                },
            )
            item_map[no_item] = obj
        self.stdout.write(self.style.SUCCESS(f"{len(ITEMS)} Item Kuesioner tersimpan (redaksi disamakan dengan kuesioner asli)"))

        count = 0
        for no_item, kode_tabel in MAPPING:
            ItemSubbab.objects.update_or_create(
                item=item_map[no_item],
                subbab=subbab_map[kode_tabel],
                defaults={"nama_kolom": NAMA_KOLOM_OVERRIDE.get(no_item, item_map[no_item].pertanyaan)},
            )
            count += 1
        self.stdout.write(self.style.SUCCESS(f"{count} pemetaan Item-Subbab tersimpan"))

        self.stdout.write(self.style.SUCCESS("Seeding data master selesai!"))